global:
  scrape_interval: 5s
  scrape_timeout: 3s
  external_labels:
      monitor: 'linux-monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'my-linux-box'
    static_configs:
      - targets: ['123.123.123.123:9100']
